#~ Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#~ By starting with 1 and 2, the first 10 terms will be:
#~ 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#~ By considering the terms in the Fibonacci sequence whose values do not exceed
#~ four million, find the sum of the even-valued terms.

def rec_Fib(n):
	if n == 0:
		return 0
	elif n == 1:
		return 1
	else:
		return rec_Fib(n-1) + rec_Fib(n-2)

x = 0
sum = 0
while (1):
	temp = rec_Fib(x)
	if (temp < 4000000):
		if ((temp % 2) == 0):
			sum += temp
			print temp
	else:
		break
	x+=1
print sum