#How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

import math

distinctPowers = []
UB=101

for a in range(2,UB):
    for b in range(2,UB):
        v = math.pow(a,b)
        if not v in distinctPowers:
            distinctPowers.append(v)

distinctPowers.sort()
print distinctPowers
print len(distinctPowers)
